export const queries = [
  { key: "carrot", label: "Carrot" },
  { key: "broccoli", label: "Broccoli" },
  { key: "asparagus", label: "Asparagus" },
  { key: "cauliflower", label: "Cauliflower" },
  { key: "corn", label: "Corn" },
  { key: "cucumber", label: "Cucumber" },
  { key: "green pepper", label: "Green Pepper" },
  { key: "lettuce", label: "Lettuce" },
  { key: "mushrooms", label: "Mushrooms" },
  { key: "onion", label: "Onion" },
  { key: "potato", label: "Potato" },
  { key: "pumpkin", label: "Pumpkin" },
  { key: "red pepper", label: "Red Pepper" },
  { key: "tomato", label: "Tomato" },
  { key: "beetroot", label: "Beetroot" },
  { key: "brussel sprouts", label: "Brussel Sprouts" },
  { key: "peas", label: "Peas" },
  { key: "zucchini", label: "Zucchini" },
  { key: "radish", label: "Radish" },
  { key: "sweet potato", label: "Sweet Potato" },
  { key: "artichoke", label: "Artichoke" },
  { key: "leek", label: "Leek" },
  { key: "cabbage", label: "Cabbage" },
  { key: "celery", label: "Celery" },
  { key: "chili", label: "Chili" },
  { key: "garlic", label: "Garlic" },
  { key: "basil", label: "Basil" },
  { key: "coriander", label: "Coriander" },
  { key: "parsley", label: "Parsley" },
  { key: "dill", label: "Dill" },
  { key: "rosemary", label: "Rosemary" },
  { key: "oregano", label: "Oregano" },
  { key: "cinnamon", label: "Cinnamon" },
  { key: "saffron", label: "Saffron" },
  { key: "green bean", label: "Green Bean" },
  { key: "bean", label: "Bean" },
  { key: "chickpea", label: "Chickpea" },
  { key: "lentil", label: "Lentil" },
  { key: "apple", label: "Apple" },
  { key: "apricot", label: "Apricot" },
  { key: "avocado", label: "Avocado" },
  { key: "banana", label: "Banana" },
  { key: "blackberry", label: "Blackberry" },
  { key: "blackcurrant", label: "Blackcurrant" },
  { key: "blueberry", label: "Blueberry" },
  { key: "boysenberry", label: "Boysenberry" },
  { key: "cherry", label: "Cherry" },
  { key: "coconut", label: "Coconut" },
  { key: "fig", label: "Fig" },
  { key: "grape", label: "Grape" },
  { key: "grapefruit", label: "Grapefruit" },
  { key: "kiwifruit", label: "Kiwifruit" },
  { key: "lemon", label: "Lemon" },
  { key: "lime", label: "Lime" },
  { key: "lychee", label: "Lychee" },
  { key: "mandarin", label: "Mandarin" },
  { key: "mango", label: "Mango" },
  { key: "melon", label: "Melon" },
  { key: "nectarine", label: "Nectarine" },
  { key: "orange", label: "Orange" },
  { key: "papaya", label: "Papaya" },
  { key: "passion fruit", label: "Passion Fruit" },
  { key: "peach", label: "Peach" },
  { key: "pear", label: "Pear" },
  { key: "pineapple", label: "Pineapple" },
  { key: "plum", label: "Plum" },
  { key: "pomegranate", label: "Pomegranate" },
  { key: "quince", label: "Quince" },
  { key: "raspberry", label: "Raspberry" },
  { key: "strawberry", label: "Strawberry" },
  { key: "watermelon", label: "Watermelon" },
  { key: "salad", label: "Salad" },
  { key: "pizza", label: "Pizza" },
  { key: "pasta", label: "Pasta" },
  { key: "popcorn", label: "Popcorn" },
  { key: "lobster", label: "Lobster" },
  { key: "steak", label: "Steak" },
  { key: "bbq", label: "Bbq" },
  { key: "pudding", label: "Pudding" },
  { key: "hamburger", label: "Hamburger" },
  { key: "pie", label: "Pie" },
  { key: "cake", label: "Cake" },
  { key: "sausage", label: "Sausage" },
  { key: "tacos", label: "Tacos" },
  { key: "kebab", label: "Kebab" },
  { key: "poutine", label: "Poutine" },
  { key: "seafood", label: "Seafood" },
  { key: "chips", label: "Chips" },
  { key: "fries", label: "Fries" },
  { key: "masala", label: "Masala" },
  { key: "paella", label: "Paella" },
  { key: "som tam", label: "Som Tam" },
  { key: "chicken", label: "Chicken" },
  { key: "toast", label: "Toast" },
  { key: "marzipan", label: "Marzipan" },
  { key: "tofu", label: "Tofu" },
  { key: "ketchup", label: "Ketchup" },
  { key: "hummus", label: "Hummus" },
  { key: "chili", label: "Chili" },
  { key: "maple syrup", label: "Maple Syrup" },
  { key: "parma ham", label: "Parma Ham" },
  { key: "fajitas", label: "Fajitas" },
  { key: "champ", label: "Champ" },
  { key: "lasagna", label: "Lasagna" },
  { key: "poke", label: "Poke" },
  { key: "chocolate", label: "Chocolate" },
  { key: "croissant", label: "Croissant" },
  { key: "arepas", label: "Arepas" },
  { key: "bunny chow", label: "Bunny Chow" },
  { key: "pierogi", label: "Pierogi" },
  { key: "donuts", label: "Donuts" },
  { key: "rendang", label: "Rendang" },
  { key: "sushi", label: "Sushi" },
  { key: "ice cream", label: "Ice Cream" },
  { key: "duck", label: "Duck" },
  { key: "curry", label: "Curry" },
  { key: "beef", label: "Beef" },
  { key: "goat", label: "Goat" },
  { key: "lamb", label: "Lamb" },
  { key: "turkey", label: "Turkey" },
  { key: "pork", label: "Pork" },
  { key: "fish", label: "Fish" },
  { key: "crab", label: "Crab" },
  { key: "bacon", label: "Bacon" },
  { key: "ham", label: "Ham" },
  { key: "pepperoni", label: "Pepperoni" },
  { key: "salami", label: "Salami" },
  { key: "ribs", label: "Ribs" },
];
